### ISSUE TITLE
Questions about MTT Theorem

### ISSUE THREAD

**Issue by QipengGuo** [klimzaporojets/consistent-EL#1]
Hi, I am working on the consistency between coreference mentions. Your paper is great and well-written. But I have a question about the calculation detail. I know KM theorem and understand up to eq. (13). However, I do not understand eq. 14 and eq. 15 clearly, why do we need to replace the first row of laplacian by the root selection weights. The paper said it equals the sum of the weights of all spanning trees connecting the nodes in a cluster. Does the cluster include the root as well? For example, c1 contains s1 and s2. But I don't think the computed score equals the spanning trees for s1 and s2 alone.

**Comment by klimzaporojets** [comment]
Dear QipengGuo, 

Thanks for your interest in our work!

I think there is a small errata in line "ground truth clusters:..." the c_1 is composed by {s_1, s_3} instead of {s_1, s_2} (this is also reflected in the Figure 2), the rest of the appendix seems to be correct. 

Indeed, all the spanning trees defining clusters are rooted in the root. For a detailed proof on why the first row needs to be replaced by root r selection weights you can refer to https://aclanthology.org/D07-1015/ (section 3.1). 

Please let us know if you have further questions, 

Best, 

Klim
