### ISSUE TITLE
number of parameters at using update2() function

### ISSUE THREAD

**Issue by asmath472** [klimzaporojets/consistent-EL#2]
Hello,

I found one code error when I tried to reproduce code.

![image](https://user-images.githubusercontent.com/59130244/186365126-9fbbd877-543d-45cc-a921-266d15752be9.png)

In my analysis, this TypeError raises at the situation when experience includes Coreference Resolution task. (only standalone-linking cases passed this error) And this occurs at the time when code tries to save trained model.

The reason of this error was here: the number of parameters in update2 was different at "/src/metrics/coref.py" and "/src/metrics/linker.py" (check following screenshots)
But I can't find the solution of this issue.

![image](https://user-images.githubusercontent.com/59130244/186365237-bcf6c2d8-e62a-4be3-afbd-18c5da40d18c.png)

![image](https://user-images.githubusercontent.com/59130244/186365264-654071dc-145e-41cf-8ac0-36320df00744.png)

 Can anyone try to reproduce this code by theirselves and check this issue? If this issue only occur on my PC, I'd like to know other PC setups.

Thanks.

**Comment by klimzaporojets** [comment]
Dear SEONHO AN, 

Thanks for your interest in our work and for raising the issue! Indeed, there was a bug due to refactoring in our original code. It has to be solved now (we are still testing this), please let us know if the issue persist or any other problem/question you may have. 

Kind regards, 

Klim
